{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lunch-map.fullname" . }}
  labels:
    {{- include "lunch-map.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "lunch-map.apiName" . }}
                port:
                  number: {{ .Values.api.port }}
          - path: /photos
            pathType: Prefix
            backend:
              service:
                name: {{ include "lunch-map.apiName" . }}
                port:
                  number: {{ .Values.api.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lunch-map.webName" . }}
                port:
                  number: {{ .Values.web.port }}
{{- end }}
